"""
Settings + local-token authentication.

Token strategy:
  - 從 .env 讀 RAG_API_TOKEN；若空，server 啟動時 generate 一個並寫進
    .env.local，前端 vite proxy 從 VITE_API_TOKEN 讀後注入 X-Local-Token。
  - 任何打到 /api/* 的 HTTP request 都會被 middleware 驗。
  - WebSocket middleware 不會 fire，所以在 handler 內手動檢查 header。

Import-time load：CORS middleware 在 add_middleware() 時就讀 allow_origins，
lifespan 太晚；所以在 module import 時就把 Settings 載好。

`_settings` is a SINGLE shared instance: `_ensure_api_token` mutates its
`api_local_token` in place at lifespan startup, and the middleware + WS handler
read that same attribute. Never re-create it elsewhere — import this object.
"""

import secrets
from pathlib import Path

from fastapi import Request, status
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from config.settings import Settings

_LOCAL_ENV_PATH = Path(".env.local")
_TOKEN_HEADER = "X-Local-Token"
_settings: Settings = Settings.from_env()


def _ensure_api_token(settings: Settings) -> str:
    """確保有個 token：env 有給就用，沒給就 generate 並寫 .env.local。"""
    if settings.api_local_token:
        return settings.api_local_token
    token = secrets.token_urlsafe(32)
    try:
        _LOCAL_ENV_PATH.write_text(
            f"# Auto-generated by RAGLoom server. Read by vite.config.ts.\n"
            f"VITE_API_TOKEN={token}\n"
        )
        print(f"[Server] Generated API token, wrote to {_LOCAL_ENV_PATH}")
    except OSError as e:
        print(f"[Server] WARNING: could not write {_LOCAL_ENV_PATH}: {e}")
        print(f"[Server] API token (set this as VITE_API_TOKEN manually): {token}")
    settings.api_local_token = token
    return token


class LocalTokenMiddleware(BaseHTTPMiddleware):
    """驗證 X-Local-Token header。CORS preflight (OPTIONS) 放行。
    若 token 尚未 ready（lifespan 未跑，例如某些 test client）視為 dev-bypass。"""

    async def dispatch(self, request: Request, call_next):
        if request.method == "OPTIONS":
            return await call_next(request)
        if not request.url.path.startswith("/api/"):
            return await call_next(request)

        expected = _settings.api_local_token
        if not expected:
            return await call_next(request)

        provided = request.headers.get(_TOKEN_HEADER, "")
        if not secrets.compare_digest(provided, expected):
            return JSONResponse(
                status_code=status.HTTP_401_UNAUTHORIZED,
                content={"detail": "invalid or missing X-Local-Token"},
            )
        return await call_next(request)
