"""
Settings + local-token authentication.

Token strategy:
  - 從 .env 讀 RAG_API_TOKEN；若空，server 啟動時 generate 一個並寫進
    .env.local，前端 vite proxy 從 VITE_API_TOKEN 讀後注入 X-Local-Token。
  - 任何打到 /api/* 的 HTTP request 都會被 middleware 驗。
  - WebSocket middleware 不會 fire，所以在 handler 內手動檢查 header。

Import-time load：CORS middleware 在 add_middleware() 時就讀 allow_origins，
lifespan 太晚；所以在 module import 時就把 Settings 載好。

`_settings` is a SINGLE shared instance: `_ensure_api_token` mutates its
`api_local_token` in place at lifespan startup, and the middleware + WS handler
read that same attribute. Never re-create it elsewhere — import this object.
"""

import base64
import secrets
from pathlib import Path
from urllib.parse import urlparse

from fastapi import Request, status
from fastapi.responses import JSONResponse, Response
from starlette.middleware.base import BaseHTTPMiddleware

from config.settings import Settings
from core import kb_crypto

_LOCAL_ENV_PATH = Path(".env.local")
_TOKEN_HEADER = "X-Local-Token"
_settings: Settings = Settings.from_env()

# 訪客 kiosk 唯一會打的 /api 端點 —— admin 密碼開啟時，只有這些免密碼。
# 其餘 /api/* 一律視為管理類，需要 admin 憑證。
_KIOSK_API: set[tuple[str, str]] = {
    ("POST", "/api/chat/query"),
    ("POST", "/api/chat/reset"),
    ("GET", "/api/profiles"),
    # KB lock bootstrap: status lets the kiosk show a "locked" banner; unlock
    # validates its own passphrase against the keystore verifier, so it must be
    # reachable before any admin credential exists (the operator may rely on the
    # unlock passphrase alone, with no RAG_ADMIN_PASSWORD set).
    ("GET", "/api/kb/status"),
    ("POST", "/api/kb/unlock"),
}


def is_kiosk_api(method: str, path: str) -> bool:
    return (method, path) in _KIOSK_API


def check_admin_auth(headers) -> bool:
    """管理類請求的憑證檢查。`headers` 是 request/websocket 的 .headers。

    放行條件（任一）：
      - Basic Auth 密碼與 RAG_ADMIN_PASSWORD 相符（操作者瀏覽器跳窗輸入，
        之後同源請求/WS 會自動帶上）。
      - 帶對的 X-Local-Token（dev vite proxy / curl，行為不變）。
    未設 RAG_ADMIN_PASSWORD → 不擋（向後相容），交還給呼叫端的其他判斷。
    """
    admin_pw = _settings.api_admin_password
    if not admin_pw:
        return True
    auth = headers.get("authorization", "")
    if auth.startswith("Basic "):
        try:
            decoded = base64.b64decode(auth[6:]).decode("utf-8", "replace")
            _, _, pw = decoded.partition(":")
            if secrets.compare_digest(pw, admin_pw):
                return True
            # Unify login + unlock: after the operator has unlocked the KB, the
            # same passphrase satisfies admin Basic Auth, so one secret covers
            # both the encryption key and the /admin gate.
            if kb_crypto.verify_passphrase(pw):
                return True
        except (ValueError, TypeError):
            pass
    token = _settings.api_local_token
    if token and secrets.compare_digest(headers.get(_TOKEN_HEADER, ""), token):
        return True
    return False


def admin_challenge() -> Response:
    """回 401 + WWW-Authenticate，讓瀏覽器跳出 Basic Auth 密碼框。"""
    return Response(
        status_code=status.HTTP_401_UNAUTHORIZED,
        content="admin authentication required",
        headers={"WWW-Authenticate": 'Basic realm="RAGLoom Admin"'},
    )


def _ensure_api_token(settings: Settings) -> str:
    """確保有個 token：env 有給就用，沒給就 generate 並寫 .env.local。"""
    if settings.api_local_token:
        return settings.api_local_token
    token = secrets.token_urlsafe(32)
    try:
        _LOCAL_ENV_PATH.write_text(
            f"# Auto-generated by RAGLoom server. Read by vite.config.ts.\n"
            f"VITE_API_TOKEN={token}\n"
        )
        print(f"[Server] Generated API token, wrote to {_LOCAL_ENV_PATH}")
    except OSError as e:
        print(f"[Server] WARNING: could not write {_LOCAL_ENV_PATH}: {e}")
        print(f"[Server] API token (set this as VITE_API_TOKEN manually): {token}")
    settings.api_local_token = token
    return token


def is_same_origin(headers) -> bool:
    """同源請求放行的判斷。`headers` 是 request 或 websocket 的 .headers（皆有 .get）。

    服務模式（FastAPI 自己以靜態檔服務前端）時，瀏覽器同源呼叫 /api/* 不會經過
    dev 的 vite proxy，也就不會被注入 X-Local-Token —— 若仍硬性要求 token，整個
    kiosk 都會 401。所以同源請求放行：Origin 的 netloc 等於 Host，或根本沒有
    Origin header（top-level 導覽 / 多數 GET）即視為同源。

    Trade-off：同機、同 origin 的本地程序（含無 Origin 的 curl）可打 API。單機
    展場可接受；訪客與 admin 的隔離靠瀏覽器 kiosk 鎖定 URL，非 app 層認證。
    跨 origin 的瀏覽器請求仍需 token —— dev 的 vite proxy 走 changeOrigin，backend
    看到 Origin=:5173 / Host=:8000 不相符，因此 dev 行為不變、照舊走 token。
    """
    origin = headers.get("origin")
    if not origin:
        return True
    return urlparse(origin).netloc == headers.get("host", "")


class LocalTokenMiddleware(BaseHTTPMiddleware):
    """驗證 X-Local-Token header。CORS preflight (OPTIONS) 放行。
    若 token 尚未 ready（lifespan 未跑，例如某些 test client）視為 dev-bypass。"""

    async def dispatch(self, request: Request, call_next):
        if request.method == "OPTIONS":
            return await call_next(request)
        if not request.url.path.startswith("/api/"):
            return await call_next(request)

        # 管理類端點：設了 admin 密碼就需要憑證，且不吃 same-origin 放行
        # （否則同源訪客脫離 kiosk 也能打）。訪客 kiosk 端點不受影響。
        if _settings.api_admin_password and not is_kiosk_api(
            request.method, request.url.path
        ):
            if not check_admin_auth(request.headers):
                return admin_challenge()
            return await call_next(request)

        expected = _settings.api_local_token
        if not expected:
            return await call_next(request)

        # 服務模式同源放行（瀏覽器不經 vite proxy、不帶 token）。
        if is_same_origin(request.headers):
            return await call_next(request)

        provided = request.headers.get(_TOKEN_HEADER, "")
        if not secrets.compare_digest(provided, expected):
            return JSONResponse(
                status_code=status.HTTP_401_UNAUTHORIZED,
                content={"detail": "invalid or missing X-Local-Token"},
            )
        return await call_next(request)
